// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHeeWQy_QlP3sKZZ_hEV39IDt68jUodA',
    appId: '1:774602819167:android:d0d36eb2a54f9abc6efdea',
    messagingSenderId: '774602819167',
    projectId: 'calma-b0a5b',
    storageBucket: 'calma-b0a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSlxrv2vQI8seXjG1zUww2Q5h1GKpcCVg',
    appId: '1:774602819167:ios:1f74109e70ade1da6efdea',
    messagingSenderId: '774602819167',
    projectId: 'calma-b0a5b',
    storageBucket: 'calma-b0a5b.firebasestorage.app',
    androidClientId: '774602819167-29dj551nkr9gqt7jgpvgvrt2pimhl1ld.apps.googleusercontent.com',
    iosClientId: '774602819167-m9ro4gcitqg94vo6omjgt6i35m81881o.apps.googleusercontent.com',
    iosBundleId: 'com.retrytech.bubbly',
  );

}